#!/usr/bin/env bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DATE="$(date +%s)"
BASE="$HOME/public_html"
INDEX="${BASE}/index.html"
INDEX_NEW="${HOME}/index-${DATE}.html"
IMAGES="$("${BASE_DIR}"/wm-docker-tags --repos)"
IMAGE_LIST=

mkdir -p "$BASE"

add_footer() {
    local page="$1"
    cat >> "$page" <<FOOT
<footer>
    <div id="powered-by">
        <a href="/"><img src="https://tools-static.wmflabs.org/toolforge/banners/Powered-by-Toolforge.png" alt="Powered by Wikimedia Toolforge"></a>
    </div>
    <a id="source" href="https://github.com/thcipriani/dockerregistry">view source</a>
</footer>
</body>
</html>
FOOT
}

make_tags_page() {
    local image="$1"
    local image_base="${BASE}/${image}/tags"

    mkdir -p "$image_base"

    local image_index="${image_base}/index.html"
    local image_index_new="${HOME}/${image//\//_}-${DATE}.html"

    python3 wm-docker-tags --image-tags "$image" --output html > "$image_index_new"

    mv "$image_index_new" "$image_index"
}


cat > "$INDEX_NEW" <<HEAD
<!doctype html5>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Wikimedia Docker - Images</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="style.css" type="text/css" />
</head>
<body>
    <h1><a href="${top_dir}">Wikimedia Docker</a> - Images</h1>
HEAD


for image in $IMAGES; do
    make_tags_page "${image}"
    IMAGE_LIST+="<li><a href=\"$image/tags/\">$image</a></li>"
done

printf '<ul>%b</ul>\n' "$IMAGE_LIST" >> "$INDEX_NEW"

add_footer "$INDEX_NEW"

cp "${BASE_DIR}/style.css" "${BASE}/style.css"

if (( $(stat -c %s "$INDEX_NEW") >= $(stat -c %s "$INDEX") )); then
    mv "$INDEX_NEW" "$INDEX"
fi
